version: '3.8'

services:
  python:
    build:
      context: .
      dockerfile: dockerfiles/python.dockerfile
    ports:
      - '5001:80'
    volumes: 
      - './backend/src:/app'
    working_dir: /app

  flutter:
    build:
      context: .
      dockerfile: dockerfiles/flutter.dockerfile
    ports:
      - '3000:80'  # Expose port for Flutter web app if needed
    volumes:
      - './coffe_app/lib:/frontend/src'